workflow:                                                                  # New in GitLab 13.5
  rules:                                                                   # Only/except are considered legacy 
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

stages:
  - test

run_tests_job:
  image: docker-registry.ebrains.eu/workflow-components/gitlab-runner
  tags:
    - docker-runner
  stage: test
  script:
#    - sudo apt install python3-venv
    #- pip install --upgrade pip
    #- pip install virtualenv
    #- python3 -m venv env
    #- source env/bin/activate
    - python3 -m pip install cwltool
    - python3 cwl_test.py
