workflow:                                                                  # New in GitLab 13.5
  rules:                                                                   # Only/except are considered legacy 
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

stages:
  - test

run_tests_job:
  tags:                                                                    # Apply runner
    - shell-runner                                                            # Replace 'my-runner' with the tag you use for your runner
  stage: test
  script:
    - sudo apt install python3-venv
#    - pip install --upgrade pip
#    - pip install virtualenv
    - python3 -m venv env
    - source env/bin/activate
    - pip install cwltool
    - python cwl_test.py                                                   # Python script to search for 'test' directories and './workflow directory
