FROM python:3.11

WORKDIR /usr/src/app
COPY ./requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt
RUN pip install cwltool

ENV PATH="/usr/src/app:$PATH"

COPY p20.CNG.swc p20.CNG.swc

CMD [ "/bin/sh" ]
