FROM python:3.11

WORKDIR /usr/src/app

RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt
RUN pip install cwltool

COPY extract_ephys_features_cli.py extract_ephys_features_cli.py
RUN chmod +x extract_ephys_features_cli.py

ENV PATH="/usr/src/app:$PATH"

CMD [ "/bin/sh" ]
