FROM python:3.11

WORKDIR /usr/src/app

RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt
RUN pip install cwltool

COPY butterworth_filter_cli.py butterworth_filter_cli.py
RUN chmod +x butterworth_filter_cli.py
COPY wavelet_transform_cli.py wavelet_transform_cli.py
RUN chmod +x wavelet_transform_cli.py

ENV PATH="/usr/src/app:$PATH"

CMD [ "/bin/sh" ]
