FROM python:3.11

WORKDIR /usr/src/app

RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir numpy neo nixio pynwb scipy tqdm elephant

COPY butter_cli.py butter_cli.py
RUN chmod +x butter_cli.py

ENV PATH="/usr/src/app:$PATH"

CMD [ "/bin/sh" ]
